name: TamBot
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blinker=1.9.0=py312h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.6.4=h6a678d5_0
  - itsdangerous=2.2.0=py312h06a4308_0
  - jinja2=3.1.6=py312h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - markupsafe=3.0.2=py312h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py312h06a4308_0
  - python=3.12.9=h5148396_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2025a=h04d1e81_0
  - werkzeug=3.1.3=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - flask==3.1.0
      - google-ai-generativelanguage==0.6.4
      - google-api-core==2.24.2
      - google-api-python-client==2.166.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.6.0
      - googleapis-common-protos==1.69.2
      - grpcio==1.71.0
      - grpcio-status==1.63.0rc1
      - grpcio-tools==1.62.3
      - h11==0.14.0
      - h2==4.2.0
      - hpack==4.1.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.28.1
      - hyperframe==6.1.0
      - idna==3.10
      - markdown==3.5
      - numpy==2.2.4
      - portalocker==2.10.1
      - proto-plus==1.26.1
      - protobuf==4.25.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pyngrok==7.2.3
      - pyparsing==3.2.3
      - pyyaml==6.0.2
      - qdrant-client==1.8.0
      - requests==2.32.3
      - rsa==4.9
      - sniffio==1.3.1
      - tqdm==4.67.1
      - typing-extensions==4.13.1
      - typing-inspection==0.4.0
      - uritemplate==4.1.1
      - urllib3==2.3.0
prefix: /home/markov/miniconda3/envs/TamBot
